"""Server-less ElectriDrive Pro licensing (Ed25519, offline verification).

The publisher holds a PRIVATE signing key (default: <config>/license_signing_key.pem)
and issues license keys with it. The app ships the matching PUBLIC key and verifies
keys offline — no license server needed. Fits a "pay what you want" donation model:
supporter donates → you `issue` a key → they paste it into the app.

A license key is ``<payload_b64url>.<signature_b64url>`` where payload is compact JSON
``{name,email,edition,issued}``.

CLI:
    python -m electridrive.licensing keygen                 # one-time: make a keypair
    python -m electridrive.licensing issue --name "Jane" --email jane@x.com
    python -m electridrive.licensing verify <KEY>
"""
from __future__ import annotations

import base64
import json
import logging
import time
from dataclasses import dataclass
from pathlib import Path

LOGGER = logging.getLogger(__name__)

# Embedded Ed25519 PUBLIC key (raw 32 bytes, base64url, no padding).
# Generated by `keygen`; replace for your own build. Public — safe to ship.
PUBLIC_KEY_B64 = "7uMvlZUF3pVw2Pu1rZ42G6Ko5_5Et4GnD7A7VguiP0g"

EDITION = "pro"


@dataclass(frozen=True)
class License:
    name: str
    email: str
    edition: str
    issued: int


def _b64e(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode().rstrip("=")


def _b64d(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def _payload_bytes(name: str, email: str, issued: int) -> bytes:
    return json.dumps(
        {"name": name, "email": email, "edition": EDITION, "issued": int(issued)},
        separators=(",", ":"), sort_keys=True,
    ).encode("utf-8")


def sign(name: str, email: str, private_key, issued: int | None = None) -> str:
    issued = int(issued if issued is not None else time.time())
    payload = _payload_bytes(name, email, issued)
    return f"{_b64e(payload)}.{_b64e(private_key.sign(payload))}"


def verify(key: str, public_key_b64: str | None = None) -> License | None:
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

        payload_b64, sig_b64 = key.strip().split(".", 1)
        payload = _b64d(payload_b64)
        pub = Ed25519PublicKey.from_public_bytes(_b64d(public_key_b64 or PUBLIC_KEY_B64))
        pub.verify(_b64d(sig_b64), payload)  # raises on mismatch/tamper
        data = json.loads(payload)
        if data.get("edition") != EDITION:
            return None
        return License(str(data.get("name", "")), str(data.get("email", "")),
                       EDITION, int(data.get("issued", 0)))
    except Exception:
        return None


def is_valid(key: str) -> bool:
    return bool(key) and verify(key) is not None


# --------------------------------------------------------------- publisher side
def generate_keypair():
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    priv = Ed25519PrivateKey.generate()
    pub_raw = priv.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    return priv, _b64e(pub_raw)


def default_private_key_path() -> Path:
    from electridrive.config import get_paths
    return get_paths().config_dir / "license_signing_key.pem"


def load_private_key(path: Path | None = None):
    from cryptography.hazmat.primitives import serialization
    p = Path(path or default_private_key_path())
    return serialization.load_pem_private_key(p.read_bytes(), password=None)


def save_private_key(priv, path: Path | None = None) -> Path:
    from cryptography.hazmat.primitives import serialization
    p = Path(path or default_private_key_path())
    pem = priv.private_bytes(serialization.Encoding.PEM,
                            serialization.PrivateFormat.PKCS8,
                            serialization.NoEncryption())
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(pem)
    p.chmod(0o600)
    return p


def main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(prog="electridrive.licensing",
                                     description="ElectriDrive Pro license tools")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("keygen", help="Create a signing keypair (writes private, prints public)")
    iss = sub.add_parser("issue", help="Issue a Pro license key")
    iss.add_argument("--name", required=True)
    iss.add_argument("--email", default="")
    ver = sub.add_parser("verify", help="Verify a license key")
    ver.add_argument("key")
    args = parser.parse_args(argv)

    if args.cmd == "keygen":
        priv, pub = generate_keypair()
        path = save_private_key(priv)
        print(f"Private key written to: {path}  (keep secret; chmod 600)")
        print(f"\nEmbed this in electridrive/licensing.py PUBLIC_KEY_B64:\n{pub}")
        return 0
    if args.cmd == "issue":
        print(sign(args.name, args.email, load_private_key()))
        return 0
    if args.cmd == "verify":
        lic = verify(args.key)
        print(f"VALID: {lic}" if lic else "INVALID")
        return 0 if lic else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
